### ISSUE TITLE
Windows 10, error Cannot read property 'length' of null

### ISSUE THREAD

**Issue by AdamWojda** [holidaypirates/nucleus#25]
When I'm trying to create styleguide with the latest version of nucleus an error appears,

node 4.5.0
npm 3.10.8
windows 10 x64

```
 Found 25 files.
C:\Users\Adam\AppData\Roaming\npm\node_modules\nucleus-styleguide\node_modules\pug-runtime\index.js:253
  throw err;
  ^

TypeError: C:\Users\Adam\AppData\Roaming\npm\node_modules\nucleus-styleguide\assets\views\common\layout.pug:21
    19|     meta(name="viewport", content="width=device-width, initial-scale=1.0")
    20|     link(href="styles/app.css",  rel="stylesheet")
  > 21|     each css in meta.css
    22|       link(href=css,  rel="stylesheet")
    23|     -if(meta.counterCss)
    24|       link(href=meta.counterCss,  rel="stylesheet")

Cannot read property 'length' of null
    at eval (eval at wrap (C:\Users\Adam\AppData\Roaming\npm\node_modules\nucleus-styleguide\node_modules\pug-runtime\wrap.js:6:10), <anonymous>:766:31)
    at eval (eval at wrap (C:\Users\Adam\AppData\Roaming\npm\node_modules\nucleus-styleguide\node_modules\pug-runtime\wrap.js:6:10), <anonymous>:781:4)
    at template (eval at wrap (C:\Users\Adam\AppData\Roaming\npm\node_modules\nucleus-styleguide\node_modules\pug-runtime\wrap.js:6:10), <anonymous>:960:142)
    at Object.exports.renderFile (C:\Users\Adam\AppData\Roaming\npm\node_modules\nucleus-styleguide\node_modules\pug\lib\index.js:410:38)
    at Object.<anonymous> (C:\Users\Adam\AppData\Roaming\npm\node_modules\nucleus-styleguide\index.js:97:19)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)

```

So, I downgraded nucleus to 1.0.4 and everything works fine, but it would be nice to use latest version.

**Comment by michaelseibt** [comment]
Hi @AdamWojda,

regarding the first issue with 'length of null', it's caused by the default config set having a wrong type for the 'css' property. It will be fixed in version 1.1.0 .

Nevertheless, I'm not sure how the above stated error is related to Nucleus. Could you please provide some more info?

Thanks in advance!

**Comment by AdamWojda** [comment]
Ok, nucleus seems to be working despite this node-gyp error, but the config file has no affect on nucleus, my settings look like this:

```
{
  "title":  "LeanStrategy",
  "files":  [
    "*.scss",
    "**/*.scss"
  ],
  "target"  : "styleguide",
  "css" : "./css/style.css",
  "template": "./styleguide-theme",
  "namespace": "page",
  "verbose" : 3,
  "counterCSS" : null,
  "staticLipsum" : false
}
```
my cli command:  "nucleus --config config.nucleus.json"

**Comment by michaelseibt** [comment]
How do you notice the config is ignored?
