### ISSUE TITLE
Windows 8: Impossible to install yet alone run

### ISSUE THREAD

**Issue by superfine** [holidaypirates/nucleus#26]
I am having unbelievable problems while trying to install Nucleus on my Windows 8 Workstation, I used `npm i -g nucleus-styleguide` to install it globally.

````
windose@WKS833 MINGW64 ~/Desktop/gitlab/nucleus-sails-starter (master)
$ npm run styleguide

> projectName-prototype@1.0.0 styleguide C:\Users\windose\Desktop\gitlab\nucleus-sails-starter
> nucleus --config config.nucleus.json


 Found 23 files.

C:\Users\windose\AppData\Roaming\npm\node_modules\nucleus-styleguide\node_modules\postcss\lib\lazy-result.js:257
        if (this.error) throw this.error;
                        ^
CssSyntaxError: <css input>:226:33: Unclosed block
    at Input.error (C:\Users\windose\AppData\Roaming\npm\node_modules\nucleus-styleguide\node_modules\postcss\lib\input.js:120:22)
    at ScssParser.unclosedBlock (C:\Users\windose\AppData\Roaming\npm\node_modules\nucleus-styleguide\node_modules\postcss\lib\parser.js:466:26)
    at ScssParser.endFile (C:\Users\windose\AppData\Roaming\npm\node_modules\nucleus-styleguide\node_modules\postcss\lib\parser.js:348:39)
    at ScssParser.loop (C:\Users\windose\AppData\Roaming\npm\node_modules\nucleus-styleguide\node_modules\postcss\lib\parser.js:87:14)
    at scssParse (C:\Users\windose\AppData\Roaming\npm\node_modules\nucleus-styleguide\node_modules\postcss-scss\lib\scss-parse.js:21:12)
    at new LazyResult (C:\Users\windose\AppData\Roaming\npm\node_modules\nucleus-styleguide\node_modules\postcss\lib\lazy-result.js:80:24)
    at Processor.process (C:\Users\windose\AppData\Roaming\npm\node_modules\nucleus-styleguide\node_modules\postcss\lib\processor.js:200:12)
    at Object.Crawler.processFile (C:\Users\windose\AppData\Roaming\npm\node_modules\nucleus-styleguide\src\Crawler.js:35:24)
    at Object.<anonymous> (C:\Users\windose\AppData\Roaming\npm\node_modules\nucleus-styleguide\index.js:59:23)
    at Module._compile (module.js:434:26)

npm ERR! Windows_NT 6.3.9600
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run" "styleguide"
npm ERR! node v4.1.1
npm ERR! npm  v2.14.4
npm ERR! code ELIFECYCLE
npm ERR! projectName-prototype@1.0.0 styleguide: `nucleus --config config.nucleus.json`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the projectName-prototype@1.0.0 styleguide script 'nucleus --config config.nucleus.json'.
npm ERR! This is most likely a problem with the projectName-prototype package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     nucleus --config config.nucleus.json
npm ERR! You can get their info via:
npm ERR!     npm owner ls projectName-prototype
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\windose\Desktop\gitlab\nucleus-sails-starter\npm-debug.log
````

````


I am running:
- Windows 8.1 Enterprise
- node v4.1.1
- npm 2.14.4

**Comment by michaelseibt** [comment]
Hi @superfine,

the first error seems related to a malformed CSS file. Unfortunately, Nucleus does not catch those errors yet and therefore does not give a clue about which file is affected. I'll change this in Version 1.1.0. Until then, try to process each file or a subset of files at once and find the misbehaving CSS.

Regarding the second one, I will need to investigate myself. Looks like the prompt is failing. Thanks for pointing this out.

**Comment by peterklein** [comment]
I also have exactly the same problems on my machine. I'm using MAC OS Sierra

**Comment by michaelseibt** [comment]
@peterklein What is the error you get? The first or the second one?
