### ISSUE TITLE
Color defined by mixin fail.

### ISSUE THREAD

**Issue by mavimo** [holidaypirates/nucleus#6]
Eg:
```
/**
 * @color Middle gray
 * @section Grayscale
 */
$middle-gray: lighten($black, 60);
```

generate:

```
 Found 27 files.
 🕐  Crawling nucleus/node_modules/color/index.js:34
			throw new Error('Unable to parse color from string "' + obj + '"');
			^

Error: Unable to parse color from string "lighten($black, 60)"
    at Object.Color (/Users/marco/Development/mavimo/nucleus/node_modules/color/index.js:34:10)
    at Color (/Users/marco/Development/mavimo/nucleus/node_modules/color/index.js:11:10)
    at Color (/Users/marco/Development/mavimo/nucleus/src/entities/Color.js:32:20)
    at Object.Transform.createEntity (/Users/marco/Development/mavimo/nucleus/src/Transform.js:121:14)
    at Object.Transform.forView (/Users/marco/Development/mavimo/nucleus/src/Transform.js:42:23)
    at Object.<anonymous> (/Users/marco/Development/mavimo/nucleus/index.js:74:29)
    at Module._compile (module.js:541:32)
    at Object.Module._extensions..js (module.js:550:10)
    at Module.load (module.js:458:32)
    at tryModuleLoad (module.js:417:12)
```

as I can see the issue is generated by color definition in [colors.pug](https://github.com/holidaypirates/nucleus/blob/master/assets/views/entities/colors.pug#L29-L30) file. I suppose we need to process (using some appropriate parser) the color definition, or (maybe easier) use a class (runtime generated) instead of color in template.

**Comment by michaelseibt** [comment]
Yes, unfortunately it's currently not possible to parse mixins as color. 

In general, it might be possible to resolve the mixin to the actual color value during one of the pipeline steps. Three options are at hand:

* Pass the file containing the mixin'd color to a SASS transpiler and extract the actual value. This would require the referenced color to be in the same file, otherwise it wouldn't be defined.

* Pass all given SASS files to a transpiler and extract the actual value. This creates a huge overhead and is not very flexible, since it would mock a whole build pipeline.

* Resolve the mixin Nucleus-wise. This would require the referenced color to be also annotated and thus visible to Nucleus.

Since the last one seems the most promising, here are some details:

* Nucleus has a small pipeline to crawl and map styles. The error above occurs after crawling for annotated styles, but just very late when the color entity is prepared for the views. 

* At this moment, we already have a list of all the colors that are visible to Nucleus. Which means, if the referenced color (in your example $black) is also annotated, we could read the value there, apply the mixin and continue with the resolved color.

I will check further implementation details and provide any progress information on this issue in the comments.

**Comment by mavimo** [comment]
I'll prefer to have opportunity to pre-process all SASS files to CSS maintaining comments  (maybe adding original variable name into CSS comment), but seems not possibile...

I think process SASS code into Nucleus can be an alternative useful in a large amount of context (colors, size, ...), I try to use node-sass to extract and process the code snippet before generate output (so we have the SASS syntax and the appropriate CSS value) but I have some issue on external file inclusion, I'm try to investigate the `resolver` option to automatically include also the required dependency but I've some issue on it. I'm also not sure is the good approach (include SASS dependency, so maybe we need also to include LESS, Stylus, ...).

**Comment by pkkummermo** [comment]
Any news on this one?

I have problems using simple variables in `@color`-blocks

```
/*
* @color Font color primary
* @section Font colors
*/
$font-color-primary: $font-color-opacity--black-87;
```

Will give me `Error: Unable to parse color from string "$font-color-opacity--black-87"`

My guess that it's the same issue?

**Comment by edbury** [comment]
@pkkummermo same issue here

This appears to happen with mixins, functions (even `rgba()`), and variable interpolation.

**Comment by luigimannoni** [comment]
No updates in 2 years yet, I wonder what are other's people approach to this? 
Is there an actual sass transpiler which only replaces variables with the final value?

**Comment by phlmn** [comment]
@luigimannoni Actually I integrated that into nucleus (https://github.com/phlmn/nucleus/tree/resolve-scss-variables). But my workflow changed since then and I'm no more using nucleus. If there is interest in that I could file a PR... It might need some cleanup though.

PS. I used sass-extract to achieve this (https://github.com/jgranstrom/sass-extract)
PPS. No LESS support…

**Comment by luigimannoni** [comment]
@phlmn actually that is more useful than you think. As we're using webpack on our workflow that puts me in the right way to give a try with the sass-extract plugin.

Happy to contribute to your PR clean up if you decide to open it later on :)
