### ISSUE TITLE
Hard to track down errors in doc blocks

### ISSUE THREAD

**Issue by evanwills** [holidaypirates/nucleus#67]
Firstly: Thanks so much for the great tool.

I'm trying to retrofit nucleus to an existing SCSS project with lots of code comments already in place none of which conform to nucleus markup.

Nucleus is throwing errors (as it should with my terrible code) but it's very hard to work out what's causing the errors or where the code is.

It would be good if Nucleus could list each file it's parsing when it starts that way, if there's an error and it fails, you can at least see which file was causing the error.

This is the output from nucleus
```
$ nucleus

 Found 252 files.
C:\Users\evan\AppData\Roaming\npm\node_modules\nucleus-styleguide\src\entities\Mixin.js:70
    var paramCode = paramString[1].match(paramCodeRE)[0];
                                                     ^

TypeError: Cannot read property '0' of null
    at Mixin.getParameters (C:\Users\evan\AppData\Roaming\npm\node_modules\nucleus-styleguide\src\entities\Mixin.js:70:54)
    at new Mixin (C:\Users\evan\AppData\Roaming\npm\node_modules\nucleus-styleguide\src\entities\Mixin.js:36:22)
    at Object.Transform.createEntity (C:\Users\evan\AppData\Roaming\npm\node_modules\nucleus-styleguide\src\Transform.js:124:14)
    at Object.Transform.forView (C:\Users\evan\AppData\Roaming\npm\node_modules\nucleus-styleguide\src\Transform.js:43:23)
    at Object.<anonymous> (C:\Users\evan\AppData\Roaming\npm\node_modules\nucleus-styleguide\index.js:74:29)
    at Module._compile (module.js:624:30)
    at Object.Module._extensions..js (module.js:635:10)
    at Module.load (module.js:545:32)
    at tryModuleLoad (module.js:508:12)
    at Function.Module._load (module.js:500:3)
```

Node: 8.7.0
NPM: 5.4.2
Nucleus: 1.1.1
Windows 10

**Comment by evanwills** [comment]
Had the same issue (with the same source code) on Windows 7 and on Ubuntu 17.04
