### ISSUE TITLE
Throwing CssSyntaxError Unclosed block on Mixin with @content

### ISSUE THREAD

**Issue by fantasma98** [holidaypirates/nucleus#9]
I'm having some trouble generating the styleguide when using a placeholder mixin

```
@mixin placeholder{
    ::-webkit-input-placeholder {@content}
    :-moz-placeholder           {@content}
    ::-moz-placeholder          {@content}
    :-ms-input-placeholder      {@content}
}
```

Compiling, throws the following error 

```
/usr/local/lib/node_modules/nucleus-styleguide/node_modules/postcss/lib/lazy-result.js:257
        if (this.error) throw this.error;
                        ^
CssSyntaxError: <css input>:1:1: Unclosed block
    at Input.error (/usr/local/lib/node_modules/nucleus-styleguide/node_modules/postcss/lib/input.js:120:22)
    at ScssParser.unclosedBlock (/usr/local/lib/node_modules/nucleus-styleguide/node_modules/postcss/lib/parser.js:466:26)
    at ScssParser.endFile (/usr/local/lib/node_modules/nucleus-styleguide/node_modules/postcss/lib/parser.js:348:39)
    at ScssParser.loop (/usr/local/lib/node_modules/nucleus-styleguide/node_modules/postcss/lib/parser.js:86:14)
    at scssParse (/usr/local/lib/node_modules/nucleus-styleguide/node_modules/postcss-scss/lib/scss-parse.js:21:12)
    at new LazyResult (/usr/local/lib/node_modules/nucleus-styleguide/node_modules/postcss/lib/lazy-result.js:80:24)
    at Processor.process (/usr/local/lib/node_modules/nucleus-styleguide/node_modules/postcss/lib/processor.js:200:12)
    at Object.Crawler.processFile (/usr/local/lib/node_modules/nucleus-styleguide/src/Crawler.js:29:24)
    at Object.<anonymous> (/usr/local/lib/node_modules/nucleus-styleguide/index.js:58:23)
    at Module._compile (module.js:413:34)
```

**Comment by michaelseibt** [comment]
Hi fantasma98!

It seems that PostCSS fails to parse the SASS file and not related to Nucleus.

Despite I did not find an explanation why, it works if you either put a ; after @content directives, or just a space in between the directive and the closing curly bracket. Both of these would work:

``` sass
@mixin placeholder {
    ::-webkit-input-placeholder { @content;}
    :-moz-placeholder           { @content;}
    ::-moz-placeholder          { @content;}
    :-ms-input-placeholder      { @content;}
}
```

``` sass
@mixin placeholder {
    ::-webkit-input-placeholder { @content }
    :-moz-placeholder           { @content }
    ::-moz-placeholder          { @content }
    :-ms-input-placeholder      { @content }
}
```

I'm closing this because it seems unrelated to Nucleus itself.

**Comment by fantasma98** [comment]
Thank you

That indeed solved the issue, however, when generating documentation for it, it triggers another error

```css
/**
 * Format the placholder of the element calling the mixin
 *
 * @mixin
 * @section Utilities
 * @example
 *  @include placeholder();
 */
@mixin placeholder {
    ::-webkit-input-placeholder { @content;}
    :-moz-placeholder           { @content;}
    ::-moz-placeholder          { @content;}
    :-ms-input-placeholder      { @content;}
}```

Throwing this error, which i think it is related to nucleus parsing of the @mixin guide.

```
var paramString = this.raw.descriptor.match(/\((.*)\)/)[1];
                                                         ^

TypeError: Cannot read property '1' of null
    at Mixin.getParameters (/usr/local/lib/node_modules/nucleus-styleguide/src/entities/Mixin.js:53:58)
    at Mixin (/usr/local/lib/node_modules/nucleus-styleguide/src/entities/Mixin.js:36:22)
    at Object.Transform.createEntity (/usr/local/lib/node_modules/nucleus-styleguide/src/Transform.js:123:14)
    at Object.Transform.forView (/usr/local/lib/node_modules/nucleus-styleguide/src/Transform.js:42:23)
    at Object.<anonymous> (/usr/local/lib/node_modules/nucleus-styleguide/index.js:73:29)
    at Module._compile (module.js:413:34)
    at Object.Module._extensions..js (module.js:422:10)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Module.require (module.js:367:17)
```

**Comment by michaelseibt** [comment]
Regarding the error, it seems like Nucleus fails because there're no brackets "()" after the mixin name. As a temporary workaround, you could try to add them to the mixin definition like `@mixin placeholder () {`?

I'll relabel this as a bug and will fix it with the next version bump.

**Comment by michaelseibt** [comment]
Yo, bumped to 1.0.6 which includes the fix. I would appreciate if you could confirm this is working for your files.

**Comment by fantasma98** [comment]
Hi @michaelseibt ,

I can confirm it's working with the latest version. 

Thank you! Great work!!
